# Generated by Django 2.2.6 on 2020-04-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syc_application', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcuteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=50, unique=True)),
                ('busniess', models.CharField(max_length=50, unique=True)),
                ('excute_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
